version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Etc/Greenwich
  open-pull-requests-limit: 99
  labels:
  - dependencies
  - worktree
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/core"
    versions:
    - ">= 0"
  - dependency-name: "@date-io/date-fns"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: size-limit
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: url-loader
    versions:
    - ">= 3.0"
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: rollup-plugin-size-snapshot
    versions:
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
    - 0.12.0
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.2
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.1
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: react-number-format
    versions:
    - 4.4.4
    - 4.5.1
    - 4.5.3
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: dtslint
    versions:
    - 4.0.6
    - 4.0.7
    - 4.0.8
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.6
    - 16.2.7
    - 16.2.9
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.3.1
  - dependency-name: cross-fetch
    versions:
    - 3.0.6
    - 3.1.0
    - 3.1.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
    - 5.1.8
  - dependency-name: svgo
    versions:
    - 2.0.3
    - 2.1.0
    - 2.2.1
    - 2.2.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.0
    - 2.2.1
    - 2.2.2
  - dependency-name: material-ui-popup-state
    versions:
    - 1.7.1
    - 1.7.2
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.19.0
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.4
    - 7.29.6
    - 7.30.0
  - dependency-name: csstype
    versions:
    - 3.0.6
    - 3.0.7
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 7.0.1
    - 7.1.0
    - 8.0.0
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
    - 2.0.0
    - 2.0.1
  - dependency-name: danger
    versions:
    - 10.6.0
    - 10.6.1
    - 10.6.2
    - 10.6.3
  - dependency-name: recharts
    versions:
    - 2.0.3
    - 2.0.4
    - 2.0.6
    - 2.0.7
    - 2.0.8
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.3.4
    - 2.4.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: emoji-regex
    versions:
    - 9.2.0
    - 9.2.1
  - dependency-name: jss
    versions:
    - 10.5.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: react-jss
    versions:
    - 10.5.1
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: pretty-bytes
    versions:
    - 5.5.0
  - dependency-name: notistack
    versions:
    - 1.0.3
    - 1.0.5
  - dependency-name: mustache
    versions:
    - 4.1.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: react-final-form
    versions:
    - 6.5.2
